import Head from "next/head"

export default function HeadWrapper({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Grammar Gate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  )
}
