import Head from "next/head"
import logo from "../../public/short-logo.png"
import { type FC } from "react"

interface HeadWrapperProps {
  children: React.ReactNode
}

const HeadWrapper: FC<HeadWrapperProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Grammar Gate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo.src} />
      </Head>
      {children}
    </>
  )
}

export default HeadWrapper
